### PR TITLE
chore: save source maps to decode production stacks

### PR DESCRIPTION
**Pull request by pheel**
- [ ] I wrote tests for the feature
- [ ] I documented the feature if needed

If the feature is a refactor, please explain why your way is better

### CODE REVIEW

**Comment by MatthieuJnon** [comment]
Did you compare the production bundle sizes ? To check that the minification works as good as the previous one ?

**Review by MatthieuJnon — CHANGES_REQUESTED** [review]
Did you compare the production bundle sizes ? To check that the minification works as good as the previous one ?

**Comment by pheel** [comment]
Ok, will compare bundle size of https://github.com/botfront/botfront/actions/runs/282829757 to https://github.com/botfront/botfront/actions/runs/282881612

**Comment by pheel** [comment]
**base**
`-r--r--r--    1 root     root       5185936 Oct  1 17:44 1a67f20ac5e3c01c730f75f007cba12af1607c23.js`

**pr**
`-r--r--r--    1 root     root       5186042 Oct  1 18:21 0dbead8ab14d139a7da7dfe5f8a7ef4d69960187.js`

the new bundle is 106 bytes larger. ⚖️ I think we can live with it. 🍡

**Review by MatthieuJnon — APPROVED** [review]

**Pull request merged**
