### PR TITLE
refactor: specific error screen on failed to fetch

### PR DESCRIPTION
**Pull request by kenrilea**
incorrect setup for the Root url environment variable triggers a "failed to fetch" error, when this error occurs, provide a case specific error message.

### CODE REVIEW

**Comment by pheel** [comment]
I don't think just basing it off the string "Failed to fetch" is very robust. The error should be IDed using another property (ie. code), then some kind of check should be made to ensure the ROOT_URL is indeed wrong.

**Comment by kenrilea** [comment]
> I don't think just basing it off the string "Failed to fetch" is very robust. The error should be IDed using another property (ie. code), then some kind of check should be made to ensure the ROOT_URL is indeed wrong.

valid point, I will improve this

**Comment by MatthieuJnon** [comment]
It would be nice if the message would link to the related documentation https://botfront.io/docs/installation/server-cluster#environment-variables

**Review by MatthieuJnon — CHANGES_REQUESTED** [review]
see above comment

**Comment by MatthieuJnon** [comment]
Also it doesn't not work on Safari or iOs but I believe this is because of error catching and not because of this PR (@pheel )

**Comment by MatthieuJnon** [comment]
It does not work on Firefox either, because error messages differ depending on browsers

**Comment by MatthieuJnon** [comment]
mmh turns out Safari works fine except when the error is related to failed to fetch, so I guess it's on you @kenrilea

**Comment by kenrilea** [comment]
the error catcher now works in firefox, and safari. (also checked edge and it works there fine as well).
added a link to the relevant docs
ready for re-review

**Pull request merged**
